# This is a basic workflow to help you get started with Actions

name: Build and push the latest build to staging

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push staging image
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest
          push: true

  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image # Will wait for the execution of the previous job
    steps:
      - uses: actions/checkout@v3

      - name: Install Helm 
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: v3.3.1 

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: mslearn-gh-pipelines-26638
          cluster-name: contoso-video

      - name: Run Helm Deploy
        run: |
          helm upgrade \
              --install \
              --create-namespace \
              --atomic \
              --wait \
              --namespace staging \
              contoso-website \
              ./kubernetes/contoso-website \
              --set image.repository=${{ secrets.ACR_NAME }} \
              --set dns.name=${{ secrets.DNS_NAME }}
